version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  gumroad-pings:
    lang: node12
    handler: ./gumroad-pings
    image: alexellis2/gumroad-pings:0.3.1
    environment:
      RAW_BODY: true
      gateway_url: http://10.62.0.1:8080/
      promotion_end_date: '2021-06-03T12:00:00.000Z'
      short_product_id: fKOcw
    secrets:
    - slack-url
    - seller-id

  gumroad-upgrade:
    lang: node12
    handler: ./gumroad-upgrade
    image: alexellis2/gumroad-upgrade:0.2.1
    environment:
      subject: "Your bonus upgrade to my video workshop"
      sender: sales@openfaas.com
      region: "eu-west-1"
    secrets:
    - ses-access-key-id
    - ses-access-token
    - seller-id
    - secret-url
