version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  gumroad-pings:
    lang: node14
    handler: ./gumroad-pings
    image: alexellis2/gumroad-pings:0.4.1
    environment:
      RAW_BODY: true
      gateway_url: http://10.62.0.1:8080/
      promotion_end_date: '2021-12-1412:00:00.000Z'
      short_product_id: fKOcw
    secrets:
    - discord-url
    - seller-id

  gumroad-upgrade:
    lang: node14
    handler: ./gumroad-upgrade
    image: alexellis2/gumroad-upgrade:0.2.3
    environment:
      subject: "You've been upgraded to my workshop!"
      sender: sales@openfaas.com
      region: "eu-west-1"
    secrets:
    - ses-access-key-id
    - ses-access-token
    - seller-id
    - secret-url
