version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  gumroad-pings:
    lang: node12
    handler: ./gumroad-pings
    image: alexellis2/gumroad-pings:0.1.1
    environment:
      RAW_BODY: true
    secrets:
    - slack-url
    - seller-id
