version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  gumroad-pings:
    lang: node20
    handler: ./gumroad-pings
    image: alexellis2/gumroad-pings:0.5.2
    environment:
      RAW_BODY: true
      gateway_url: http://10.62.0.1:8080/
      promotion_end_date: '2022-08-29 12:00:00.000Z'
      short_product_id: fKOcw
    secrets:
    - discord-url
    - seller-id

  gumroad-upgrade:
    lang: node20
    handler: ./gumroad-upgrade
    image: alexellis2/gumroad-upgrade:0.2.4
    environment:
      subject: "You've been upgraded to my OpenFaaS video workshop!"
      sender: sales@openfaas.com
      region: "eu-west-1"
    secrets:
    - ses-access-key-id
    - ses-access-token
    - seller-id
    - secret-url
